FROM docker.io/library/rust:latest AS rust
FROM quay.io/pierreprinetti/fedora-toolbox:35

COPY --from=rust \
	/usr/local/cargo/bin/rustc \
	/usr/local/cargo/bin/rustup \
	/usr/local/cargo/bin/cargo \
	/usr/bin/

RUN dnf -y install \
	ShellCheck \
	ansible \
	bind-utils \
	git-crypt \
	golang \
	python3-octaviaclient
