FROM docker.io/library/rust:latest AS rust
FROM quay.io/pierreprinetti/fedora-toolbox:36

COPY --from=rust \
	/usr/local/cargo/bin/rustc \
	/usr/local/cargo/bin/rustup \
	/usr/local/cargo/bin/cargo \
	/usr/bin/

RUN \
	dnf -y copr enable agriffis/neovim-nightly \
	&& dnf -y upgrade \
	&& dnf -y install \
		ShellCheck \
		ansible \
		bind-utils \
		git-crypt \
		golang \
		jq \
		nodejs \
		openssl-devel \
		python3-octaviaclient \
		python3-pip \
		vim-common
