FROM registry.fedoraproject.org/fedora-toolbox:35
RUN dnf -y upgrade
RUN dnf -y install \
	fd-find \
	fzf \
	make \
	mosh \
	neovim \
	python3-neovim \
	ripgrep \
	task \
	tmate \
	tmux \
	wl-clipboard \
	zsh \
	z
RUN echo 'export ZDOTDIR="${XDG_CONFIG_HOME:-${HOME}/.config}/zsh"' >> /etc/zshenv

RUN dnf install -y https://prerelease.keybase.io/keybase_amd64.rpm
